### ISSUE TITLE
Add "endif" to fix build no recipe issue

### ISSUE THREAD

**Issue by cydia2020** [PureNexusProject/android_vendor_pure#2]
# Camera Effects for devices without a vendor partition
ifneq ($(filter shamu,$(TARGET_PRODUCT)),)
PRODUCT_COPY_FILES +=  \
    vendor/pure/prebuilt/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/pure/prebuilt/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
**endif** _< add this_

# Proprietary latinime libs needed for Keyboard swyping
ifneq ($(filter shamu,$(TARGET_PRODUCT)),)
PRODUCT_COPY_FILES += \
    vendor/pure/prebuilt/lib/libjni_latinime.so:system/lib/libjni_latinime.so
else
PRODUCT_COPY_FILES += \
    vendor/pure/prebuilt/lib64/libjni_latinime.so:system/lib64/libjni_latinime.so
endif

**Comment by cydia2020** [comment]
I cannot pull request for now, so only this way, sorry

**Comment by beanstown106** [comment]
thanks my bad will ammend
